### PR TITLE
Change JEVOIS_SRC_ROOT to allow building in locations other than HOME

### PR DESCRIPTION
**Pull request by pelrun**
JEVOIS_SRC_ROOT was inconsistently applied (requiring it to be ${HOME}/jevois for things to work) and was pointing into the jevois repo dir, requiring some dodgy relative path manipulation. I've changed all references to ${HOME} or ~ to use JEVOIS_SRC_ROOT and also redefined it to be the parent path of jevois/jevoisbase/jevois-sdk.

There's another pull request in jevoisbase (https://github.com/jevois/jevoisbase/pull/2) that will need to be merged at the same time, and the updated jevois-easy-install.sh script is here: https://gist.github.com/pelrun/bdd3c09c22d25cfe4dae8e83f05f3aae

### CODE REVIEW

**Comment by jevois** [comment]
Thanks!

**Comment by pelrun** [comment]
I don't know how you managed this, but you've pushed changes to my fork and undone the documentation changes around the bugfix PR, which is still waiting to be pulled into jevois-sdk...

**Comment by jevois** [comment]
Oh, my bad, i did not see your other PRs in jevoisbase and jevois-sdk. So after i merged the one here i saw that the TBB, etc problems still remained and put those steps back into the doc in a subsequent commit. Maybe you just pulled that commit into your branch? I will merge your other PRs as soon as i can and fix the doc again. Many thanks again by the way, those patches in the sdk are great to avoid the manual fixing steps!

**Comment by pelrun** [comment]
No, I haven't touched my repos for a few days. After a bit of investigation, I discovered github gives the owners of the upstream repo push access to the branch a PR is in unless you specifically disable it (the checkbox is hidden in the bottom corner of the PR page) It's a surprise to me!

**Pull request merged**
